import {
  CoursesPage,
  InfoPage,
  AutoMechanic,
  Backend,
  Exploitation,
  Frontend,
  Information,
  Main,
  MechRob,
  MobileDevelopment,
  SisAdm,
  TD,
  LDocs,
  About,
  Teacherinfo,
  Students,
  NPA,
  NewsCards,
  News,
  LoginPage,
  AdminPage,
  MainAdmin,
  CoursesAdmin,
  InfoAdmin,
  NewsAdmin,
  PlitAdmin,
  InternalPagesAdmin,
  TeacherSl,
} from "../pages";

const routes = [
  { path: "/", element: <Main /> },
  { path: "/courses", element: <CoursesPage /> },
  { path: "/info", element: <InfoPage /> },
  { path: "/fr", element: <Frontend /> },
  { path: "/br", element: <Backend /> },
  { path: "/mr", element: <MechRob /> },
  { path: "/md", element: <MobileDevelopment /> },
  { path: "/sa", element: <SisAdm /> },
  { path: "/td", element: <TD /> },
  { path: "/am", element: <AutoMechanic /> },
  { path: "/in", element: <Information /> },
  { path: "/ex", element: <Exploitation /> },
  { path: "/info/applicant", element: <Students /> },
  { path: "/info/docs", element: <LDocs /> },
  { path: "/info/npa", element: <NPA /> },
  { path: "/plit/teachers", element: <TeacherSl /> },
  { path: "/plit/teachers/:id", element: <Teacherinfo /> },
  { path: "/news", element: <NewsCards /> },
  { path: "/news/:id", element: <News /> },
  { path: "/plit/about", element: <About /> },
  {
    path: "/admin",
    children: [
      { path: "sign", element: <LoginPage /> }, // Страница входа
      { path: "main", element: <AdminPage /> }, // Страница админки
      { path: "home", element: <MainAdmin /> },
      { path: "courses", element: <CoursesAdmin /> },
      { path: "information", element: <InfoAdmin /> },
      { path: "news", element: <NewsAdmin /> },
      { path: "plit", element: <PlitAdmin /> },
      { path: "internal-pages", element: <InternalPagesAdmin /> },
    ],
  },
];

export default routes;
