import {
  CoursesPage,
  InfoPage,
  AutoMechanic,
  Backend,
  Exploitation,
  Frontend,
  Information,
  Main,
  MechRob,
  MobileDevelopment,
  SisAdm,
  TD,
  LDocs,
  About,
  Teacherinfo,
  Students,
  NPA,
  AdminPanel,
  KyrgyzstanTours,
  AddTour,
  AdminAbout,
  CentralAsiaTours,
  TourDetail,
  Pictures,
  Video,
  StaffDetails,
} from "../pages";

const routes = [
  { path: "/", element: <Main /> },
  { path: "/courses", element: <CoursesPage /> },
  { path: "/info", element: <InfoPage /> },
  { path: "/fr", element: <Frontend /> },
  { path: "/br", element: <Backend /> },
  { path: "/mr", element: <MechRob /> },
  { path: "/md", element: <MobileDevelopment /> },
  { path: "/sa", element: <SisAdm /> },
  { path: "/td", element: <TD /> },
  { path: "/am", element: <AutoMechanic /> },
  { path: "/in", element: <Information /> },
  { path: "/ex", element: <Exploitation /> },
  { path: "/info/applicant", element: <Students /> },
  { path: "/info/npa", element: <NPA /> },
  { path: "/info/docs", element: <LDocs /> },
  { path: "/plit/teachers/:id", element: <Teacherinfo /> },
  { path: "/plit/about", element: <About /> },
  { path: "/admin/sign", element: <AdminPanel /> },
  { path: "/admin/tours/kyrgyzstan", element: <KyrgyzstanTours /> },
  { path: "/admin/tours/addKGTours", element: <AddTour /> },
  { path: "/admin/tours/addCentralAsiaTours", element: <AddTour /> },
  { path: "/admin/tours/centralAsia", element: <CentralAsiaTours /> },
  { path: "/admin/staff", element: <AdminAbout /> },
  { path: "/admin/pictures", element: <Pictures /> },
  { path: "/admin/video", element: <Video /> },
  { path: "/admin/tour_detail/:id", element: <TourDetail /> },
  { path: "/admin/staff_details/:id", element: <StaffDetails /> },
];
export default routes;
