export { CoursesPage } from "./HeaderPages/CouresPage.async";
import AdminAbout from "./adminpages/AdminAbout";
export { InfoPage } from "./HeaderPages/InfoPage.async";
export { Main } from "./Main/Main.async";
export { Frontend } from "./directions/Frontend.async";
export { TD } from "./directions/TD.async";
export { SisAdm } from "./directions/SisAdm.async";
export { Backend } from "./directions/Backend.async";
export { MechRob } from "./directions/MechRob.async";
export { MobileDevelopment } from "./directions/MobileDevelopment.async";
export { Information } from "./directions/Information.async";
export { Exploitation } from "./directions/Exploitation.async";
export { AutoMechanic } from "./directions/AutoMechanic.async";
export { News } from "./news/News.async";
export { NewsCards } from "./news/NewsCards.async";
export { LDocs } from "./HeaderPages/LDocs.async";
export { About } from "./about/About.async";
export { Teacherinfo } from "./HeaderPages/Teacherinfo.async";
export { TeacherSl } from "../components/teachersSlider/TeacherSl.async";
export { Students } from "./HeaderPages/Students.async";
export { NPA } from "./HeaderPages/NPA.async";
export { default as AdminPage } from "../pages/adminpages/AdminPage";
export { default as HomeAdmin } from "./adminpages/HomeAdmin";
export { default as CoursesAdmin } from "../pages/adminpages/CoursesAdmin";
export { default as InfoAdmin } from "../pages/adminpages/InfoAdmin";
export { default as NewsAdmin } from "../pages/adminpages/NewsAdmin";
export { default as PlitAdmin } from "../pages/adminpages/PlitAdmin";
export { default as AdminApplicant } from "../pages/adminpages/AdminApplicant";
export { default as AdminAbout } from "../pages/adminpages/AdminAbout";
export { default as InternalPagesAdmin } from "../pages/adminpages/InternalPagesAdmin";
export { default as LoginPage } from "./adminpages/LoginPage";
