export { HomePage } from "./HeaderPages/HomePage.async";
export { CoursesPage } from "./HeaderPages/CouresPage.async";
export { InfoPage } from "./HeaderPages/InfoPage.async";
0;
export { Main } from "./Main/Main.async";
export { Frontend } from "./directions/Frontend.async";
export { TD } from "./directions/TD.async";
export { SisAdm } from "./directions/SisAdm.async";
export { Backend } from "./directions/Backend.async";
export { MechRob } from "./directions/MechRob.async";
export { MobileDevelopment } from "./directions/MobileDevelopment.async";
export { Information } from "./directions/Information.async";
export { Exploitation } from "./directions/Exploitation.async";
export { AutoMechanic } from "./directions/AutoMechanic.async";
export { LDocs } from "./HeaderPages/LDocs.async";
